version: "3.8"

services:
  eyesonground-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eyesonground-frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eyesonground.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.eyesonground.tls=true"
      - "traefik.http.routers.eyesonground.tls.certresolver=letsencrypt"
      - "traefik.http.services.eyesonground.loadbalancer.server.port=8080"
